### ISSUE TITLE
/rest/default/V1/guest-carts/<card_id>/payment-information:1 Failed to load resource: the server responded with a status of 400 (Bad Request)

### ISSUE THREAD

**Issue by blopa** [wirecardBrasil/magento2#35]
Boa noite, pessoal.

Estou tentando utilizar o modulo em uma nova instalação do Magento 2.3.0 e estou recebendo esse erro ao tentar finalizar um pedido por boleto:

Request URL: http://localhost.dev/rest/default/V1/guest-carts/KMpVa4t5XMP9D98PBxSQVfSpHeG4rKcS/payment-information
Request Method: POST
Status Code: 400 Bad Request
Remote Address: 127.0.0.1:80
Referrer Policy: no-referrer-when-downgrade

Estou usando o ambiente sandbox. Alguma idéia do porque do problema?

Obrigado

**Comment by blopa** [comment]
Aparentemente o trace do problema é esse:

```#0 /home/mylocal/local/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder(\'8xoCCyA7Ip2znyF...\', \'montenegro.pabl...\', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address))
#1 /home/mylocal/local/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->___callParent(\'savePaymentInfo...\', Array)
#2 /home/mylocal/local/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->Magento\\Framework\\Interception\\{closure}(\'8xoCCyA7Ip2znyF...\', \'montenegro.pabl...\', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address))
#3 /home/mylocal/local/public_html/generated/code/Magento/Checkout/Model/GuestPaymentInformationManagement/Interceptor.php(26): Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->___callPlugins(\'savePaymentInfo...\', Array, Array)
#4 [internal function]: Magento\\Checkout\\Model\\GuestPaymentInformationManagement\\Interceptor->savePaymentInformationAndPlaceOrder(\'8xoCCyA7Ip2znyF...\', \'montenegro.pabl...\', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address))
#5 /home/mylocal/local/public_html/vendor/magento/module-webapi/Controller/Rest/SynchronousRequestProcessor.php(95): call_user_func_array(Array, Array)
#6 /home/mylocal/local/public_html/vendor/magento/module-webapi/Controller/Rest.php(188): Magento\\Webapi\\Controller\\Rest\\SynchronousRequestProcessor->process(Object(Magento\\Framework\\Webapi\\Rest\\Request\\Proxy))
#7 /home/mylocal/local/public_html/vendor/magento/framework/Interception/Interceptor.php(58): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))
#8 /home/mylocal/local/public_html/vendor/magento/framework/Interception/Interceptor.php(138): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callParent(\'dispatch\', Array)
#9 /home/mylocal/local/public_html/vendor/magento/framework/Interception/Interceptor.php(153): Magento\\Webapi\\Controller\\Rest\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Request\\Http))
#10 /home/mylocal/local/public_html/generated/code/Magento/Webapi/Controller/Rest/Interceptor.php(26): Magento\\Webapi\\Controller\\Rest\\Interceptor->___callPlugins(\'dispatch\', Array, Array)
#11 /home/mylocal/local/public_html/vendor/magento/framework/App/Http.php(135): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))
#12 /home/mylocal/local/public_html/vendor/magento/framework/App/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()
#13 /home/mylocal/local/public_html/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http\\Interceptor))```

**Comment by elisei** [comment]
Olá @blopa ,

Por favor atualize o módulo.

**Comment by blopa** [comment]
Obrigado pela resposta rapida, porem infelizmente nao funcionou.

Voces tem alguma previsao para quando o modulo vai ser compativel com Magento 2.3.0? 

Obrigado

**Comment by elisei** [comment]
@blopa o módulo já é compativel e nossa loja demo http://magento2.loja.ninja/ já roda nessa versão.

**Comment by blopa** [comment]
Uhmnn descobri o problema. Se o CPF estiver vazio ou for invalido, acontece esse erro. O ruim eh que nao aparece nenhuma mensagem de erro, soh falha a call com 400, mas nao retorna nenhuma mensagem de erro, logo nada eh exibido no frontend.

Tem como arrumar isso?

Obrigado

**Comment by blopa** [comment]
Ou entao aceitar qualquer valor no campo do CPF, porque as vezes os clientes digitam qualquer coisa e podemos perder vendas por causa disso
